// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: audit.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertAudit = `-- name: InsertAudit :exec
INSERT INTO audit_logs (actor_user_id, action, entity, entity_id)
VALUES ($1,$2,$3,$4)
`

type InsertAuditParams struct {
	ActorUserID pgtype.UUID `json:"actor_user_id"`
	Action      string      `json:"action"`
	Entity      string      `json:"entity"`
	EntityID    pgtype.UUID `json:"entity_id"`
}

func (q *Queries) InsertAudit(ctx context.Context, arg InsertAuditParams) error {
	_, err := q.db.Exec(ctx, insertAudit,
		arg.ActorUserID,
		arg.Action,
		arg.Entity,
		arg.EntityID,
	)
	return err
}

const listAudit = `-- name: ListAudit :many
SELECT id, actor_user_id, action, entity, entity_id, created_at FROM audit_logs ORDER BY created_at DESC
`

func (q *Queries) ListAudit(ctx context.Context) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAudit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditLog
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.ActorUserID,
			&i.Action,
			&i.Entity,
			&i.EntityID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
