// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: consent_files.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createConsentFile = `-- name: CreateConsentFile :exec
INSERT INTO consent_files (user_id, consent_type, file_url, file_size, mime_type)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (user_id, consent_type) DO UPDATE SET
  file_url = EXCLUDED.file_url,
  file_size = EXCLUDED.file_size,
  mime_type = EXCLUDED.mime_type,
  uploaded_at = now()
`

type CreateConsentFileParams struct {
	UserID      uuid.UUID   `json:"user_id"`
	ConsentType string      `json:"consent_type"`
	FileUrl     string      `json:"file_url"`
	FileSize    pgtype.Int8 `json:"file_size"`
	MimeType    pgtype.Text `json:"mime_type"`
}

func (q *Queries) CreateConsentFile(ctx context.Context, arg CreateConsentFileParams) error {
	_, err := q.db.Exec(ctx, createConsentFile,
		arg.UserID,
		arg.ConsentType,
		arg.FileUrl,
		arg.FileSize,
		arg.MimeType,
	)
	return err
}

const deleteConsentFile = `-- name: DeleteConsentFile :exec
DELETE FROM consent_files WHERE user_id = $1 AND consent_type = $2
`

type DeleteConsentFileParams struct {
	UserID      uuid.UUID `json:"user_id"`
	ConsentType string    `json:"consent_type"`
}

func (q *Queries) DeleteConsentFile(ctx context.Context, arg DeleteConsentFileParams) error {
	_, err := q.db.Exec(ctx, deleteConsentFile, arg.UserID, arg.ConsentType)
	return err
}

const getConsentFile = `-- name: GetConsentFile :one
SELECT id, user_id, consent_type, file_url, file_size, mime_type, uploaded_at
FROM consent_files
WHERE user_id = $1 AND consent_type = $2
`

type GetConsentFileParams struct {
	UserID      uuid.UUID `json:"user_id"`
	ConsentType string    `json:"consent_type"`
}

func (q *Queries) GetConsentFile(ctx context.Context, arg GetConsentFileParams) (ConsentFile, error) {
	row := q.db.QueryRow(ctx, getConsentFile, arg.UserID, arg.ConsentType)
	var i ConsentFile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ConsentType,
		&i.FileUrl,
		&i.FileSize,
		&i.MimeType,
		&i.UploadedAt,
	)
	return i, err
}

const getConsentFilesByUser = `-- name: GetConsentFilesByUser :many
SELECT id, user_id, consent_type, file_url, file_size, mime_type, uploaded_at
FROM consent_files
WHERE user_id = $1
ORDER BY consent_type
`

func (q *Queries) GetConsentFilesByUser(ctx context.Context, userID uuid.UUID) ([]ConsentFile, error) {
	rows, err := q.db.Query(ctx, getConsentFilesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ConsentFile
	for rows.Next() {
		var i ConsentFile
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ConsentType,
			&i.FileUrl,
			&i.FileSize,
			&i.MimeType,
			&i.UploadedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
