// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: email_tokens.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createEmailToken = `-- name: CreateEmailToken :exec
INSERT INTO email_verify_tokens (user_id, token_hash, expires_at)
VALUES ($1, $2, $3)
`

type CreateEmailTokenParams struct {
	UserID    uuid.UUID `json:"user_id"`
	TokenHash string    `json:"token_hash"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) CreateEmailToken(ctx context.Context, arg CreateEmailTokenParams) error {
	_, err := q.db.Exec(ctx, createEmailToken, arg.UserID, arg.TokenHash, arg.ExpiresAt)
	return err
}

const getEmailTokenByHash = `-- name: GetEmailTokenByHash :one
SELECT id, user_id, token_hash, expires_at, used_at, created_at FROM email_verify_tokens WHERE token_hash = $1
`

func (q *Queries) GetEmailTokenByHash(ctx context.Context, tokenHash string) (EmailVerifyToken, error) {
	row := q.db.QueryRow(ctx, getEmailTokenByHash, tokenHash)
	var i EmailVerifyToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const markEmailTokenUsed = `-- name: MarkEmailTokenUsed :exec
UPDATE email_verify_tokens SET used_at = now() WHERE id = $1
`

func (q *Queries) MarkEmailTokenUsed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markEmailTokenUsed, id)
	return err
}
