// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: exports.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const exportParticipants = `-- name: ExportParticipants :many
SELECT
  p.surname || ' ' || p.name || ' ' || p.patronymic AS full_name,
  p.affiliation,
  p.city,
  u.email
FROM profiles p
JOIN users u ON u.id = p.user_id
WHERE u.status = 'APPROVED'
`

type ExportParticipantsRow struct {
	FullName    interface{} `json:"full_name"`
	Affiliation string      `json:"affiliation"`
	City        string      `json:"city"`
	Email       string      `json:"email"`
}

func (q *Queries) ExportParticipants(ctx context.Context) ([]ExportParticipantsRow, error) {
	rows, err := q.db.Query(ctx, exportParticipants)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExportParticipantsRow
	for rows.Next() {
		var i ExportParticipantsRow
		if err := rows.Scan(
			&i.FullName,
			&i.Affiliation,
			&i.City,
			&i.Email,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const exportTalks = `-- name: ExportTalks :many
SELECT
  t.title,
  t.kind,
  t.authors,
  t.abstract,
  s.title_ru AS section,
  p.surname || ' ' || p.name || ' ' || p.patronymic AS speaker
FROM talks t
JOIN profiles p ON p.user_id = t.speaker_user_id
LEFT JOIN sections s ON s.id = t.section_id
`

type ExportTalksRow struct {
	Title    string      `json:"title"`
	Kind     string      `json:"kind"`
	Authors  []byte      `json:"authors"`
	Abstract string      `json:"abstract"`
	Section  pgtype.Text `json:"section"`
	Speaker  interface{} `json:"speaker"`
}

func (q *Queries) ExportTalks(ctx context.Context) ([]ExportTalksRow, error) {
	rows, err := q.db.Query(ctx, exportTalks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExportTalksRow
	for rows.Next() {
		var i ExportTalksRow
		if err := rows.Scan(
			&i.Title,
			&i.Kind,
			&i.Authors,
			&i.Abstract,
			&i.Section,
			&i.Speaker,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
