// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: materials.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createMaterial = `-- name: CreateMaterial :one
INSERT INTO materials (type, title_ru, title_en, description_ru, description_en, file_url, file_size, mime_type, uploaded_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, type, title_ru, title_en, description_ru, description_en, file_url, file_size, mime_type, uploaded_by, created_at, updated_at
`

type CreateMaterialParams struct {
	Type          string      `json:"type"`
	TitleRu       string      `json:"title_ru"`
	TitleEn       string      `json:"title_en"`
	DescriptionRu pgtype.Text `json:"description_ru"`
	DescriptionEn pgtype.Text `json:"description_en"`
	FileUrl       string      `json:"file_url"`
	FileSize      pgtype.Int8 `json:"file_size"`
	MimeType      pgtype.Text `json:"mime_type"`
	UploadedBy    pgtype.UUID `json:"uploaded_by"`
}

func (q *Queries) CreateMaterial(ctx context.Context, arg CreateMaterialParams) (Material, error) {
	row := q.db.QueryRow(ctx, createMaterial,
		arg.Type,
		arg.TitleRu,
		arg.TitleEn,
		arg.DescriptionRu,
		arg.DescriptionEn,
		arg.FileUrl,
		arg.FileSize,
		arg.MimeType,
		arg.UploadedBy,
	)
	var i Material
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.TitleRu,
		&i.TitleEn,
		&i.DescriptionRu,
		&i.DescriptionEn,
		&i.FileUrl,
		&i.FileSize,
		&i.MimeType,
		&i.UploadedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteMaterial = `-- name: DeleteMaterial :exec
DELETE FROM materials
WHERE id = $1
`

func (q *Queries) DeleteMaterial(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteMaterial, id)
	return err
}

const getMaterial = `-- name: GetMaterial :one
SELECT id, type, title_ru, title_en, description_ru, description_en, file_url, file_size, mime_type, uploaded_by, created_at, updated_at
FROM materials
WHERE id = $1
`

func (q *Queries) GetMaterial(ctx context.Context, id uuid.UUID) (Material, error) {
	row := q.db.QueryRow(ctx, getMaterial, id)
	var i Material
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.TitleRu,
		&i.TitleEn,
		&i.DescriptionRu,
		&i.DescriptionEn,
		&i.FileUrl,
		&i.FileSize,
		&i.MimeType,
		&i.UploadedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listMaterials = `-- name: ListMaterials :many
SELECT id, type, title_ru, title_en, description_ru, description_en, file_url, file_size, mime_type, uploaded_by, created_at, updated_at
FROM materials
ORDER BY created_at DESC
`

func (q *Queries) ListMaterials(ctx context.Context) ([]Material, error) {
	rows, err := q.db.Query(ctx, listMaterials)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Material
	for rows.Next() {
		var i Material
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.TitleRu,
			&i.TitleEn,
			&i.DescriptionRu,
			&i.DescriptionEn,
			&i.FileUrl,
			&i.FileSize,
			&i.MimeType,
			&i.UploadedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMaterialsByType = `-- name: ListMaterialsByType :many
SELECT id, type, title_ru, title_en, description_ru, description_en, file_url, file_size, mime_type, uploaded_by, created_at, updated_at
FROM materials
WHERE type = $1
ORDER BY created_at DESC
`

func (q *Queries) ListMaterialsByType(ctx context.Context, type_ string) ([]Material, error) {
	rows, err := q.db.Query(ctx, listMaterialsByType, type_)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Material
	for rows.Next() {
		var i Material
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.TitleRu,
			&i.TitleEn,
			&i.DescriptionRu,
			&i.DescriptionEn,
			&i.FileUrl,
			&i.FileSize,
			&i.MimeType,
			&i.UploadedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMaterial = `-- name: UpdateMaterial :one
UPDATE materials
SET type = $2, title_ru = $3, title_en = $4, description_ru = $5, description_en = $6, file_url = $7, file_size = $8, mime_type = $9, updated_at = now()
WHERE id = $1
RETURNING id, type, title_ru, title_en, description_ru, description_en, file_url, file_size, mime_type, uploaded_by, created_at, updated_at
`

type UpdateMaterialParams struct {
	ID            uuid.UUID   `json:"id"`
	Type          string      `json:"type"`
	TitleRu       string      `json:"title_ru"`
	TitleEn       string      `json:"title_en"`
	DescriptionRu pgtype.Text `json:"description_ru"`
	DescriptionEn pgtype.Text `json:"description_en"`
	FileUrl       string      `json:"file_url"`
	FileSize      pgtype.Int8 `json:"file_size"`
	MimeType      pgtype.Text `json:"mime_type"`
}

func (q *Queries) UpdateMaterial(ctx context.Context, arg UpdateMaterialParams) (Material, error) {
	row := q.db.QueryRow(ctx, updateMaterial,
		arg.ID,
		arg.Type,
		arg.TitleRu,
		arg.TitleEn,
		arg.DescriptionRu,
		arg.DescriptionEn,
		arg.FileUrl,
		arg.FileSize,
		arg.MimeType,
	)
	var i Material
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.TitleRu,
		&i.TitleEn,
		&i.DescriptionRu,
		&i.DescriptionEn,
		&i.FileUrl,
		&i.FileSize,
		&i.MimeType,
		&i.UploadedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
