// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AuditLog struct {
	ID          uuid.UUID   `json:"id"`
	ActorUserID pgtype.UUID `json:"actor_user_id"`
	Action      string      `json:"action"`
	Entity      string      `json:"entity"`
	EntityID    pgtype.UUID `json:"entity_id"`
	CreatedAt   time.Time   `json:"created_at"`
}

type ConsentFile struct {
	ID          uuid.UUID   `json:"id"`
	UserID      uuid.UUID   `json:"user_id"`
	ConsentType string      `json:"consent_type"`
	FileUrl     string      `json:"file_url"`
	FileSize    pgtype.Int8 `json:"file_size"`
	MimeType    pgtype.Text `json:"mime_type"`
	UploadedAt  time.Time   `json:"uploaded_at"`
}

type EmailVerifyToken struct {
	ID        uuid.UUID          `json:"id"`
	UserID    uuid.UUID          `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt time.Time          `json:"expires_at"`
	UsedAt    pgtype.Timestamptz `json:"used_at"`
	CreatedAt time.Time          `json:"created_at"`
}

type Material struct {
	ID            uuid.UUID   `json:"id"`
	Type          string      `json:"type"`
	TitleRu       string      `json:"title_ru"`
	TitleEn       string      `json:"title_en"`
	DescriptionRu pgtype.Text `json:"description_ru"`
	DescriptionEn pgtype.Text `json:"description_en"`
	FileUrl       string      `json:"file_url"`
	FileSize      pgtype.Int8 `json:"file_size"`
	MimeType      pgtype.Text `json:"mime_type"`
	UploadedBy    pgtype.UUID `json:"uploaded_by"`
	CreatedAt     time.Time   `json:"created_at"`
	UpdatedAt     time.Time   `json:"updated_at"`
}

type News struct {
	ID          uuid.UUID `json:"id"`
	TitleRu     string    `json:"title_ru"`
	BodyRu      string    `json:"body_ru"`
	TitleEn     string    `json:"title_en"`
	BodyEn      string    `json:"body_en"`
	Pinned      bool      `json:"pinned"`
	PublishedAt time.Time `json:"published_at"`
}

type PageContent struct {
	ID        uuid.UUID `json:"id"`
	Slug      string    `json:"slug"`
	TitleRu   string    `json:"title_ru"`
	BodyRu    string    `json:"body_ru"`
	TitleEn   string    `json:"title_en"`
	BodyEn    string    `json:"body_en"`
	UpdatedAt time.Time `json:"updated_at"`
}

type Profile struct {
	UserID                uuid.UUID   `json:"user_id"`
	Surname               string      `json:"surname"`
	Name                  string      `json:"name"`
	Patronymic            string      `json:"patronymic"`
	BirthDate             time.Time   `json:"birth_date"`
	City                  string      `json:"city"`
	AcademicDegree        pgtype.Text `json:"academic_degree"`
	Affiliation           string      `json:"affiliation"`
	Position              string      `json:"position"`
	Phone                 string      `json:"phone"`
	PostalAddress         string      `json:"postal_address"`
	ConsentDataProcessing bool        `json:"consent_data_processing"`
	ConsentDataTransfer   bool        `json:"consent_data_transfer"`
	UpdatedAt             time.Time   `json:"updated_at"`
}

type RefreshSession struct {
	ID        uuid.UUID          `json:"id"`
	UserID    uuid.UUID          `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
	ExpiresAt time.Time          `json:"expires_at"`
	CreatedAt time.Time          `json:"created_at"`
}

type Role struct {
	ID   uuid.UUID `json:"id"`
	Code string    `json:"code"`
}

type Section struct {
	ID        uuid.UUID `json:"id"`
	TitleRu   string    `json:"title_ru"`
	TitleEn   string    `json:"title_en"`
	SortOrder int32     `json:"sort_order"`
}

type Talk struct {
	ID            uuid.UUID          `json:"id"`
	SpeakerUserID uuid.UUID          `json:"speaker_user_id"`
	SectionID     pgtype.UUID        `json:"section_id"`
	Title         string             `json:"title"`
	Affiliation   string             `json:"affiliation"`
	Abstract      string             `json:"abstract"`
	Kind          string             `json:"kind"`
	Authors       []byte             `json:"authors"`
	ScheduleTime  pgtype.Timestamptz `json:"schedule_time"`
	FileUrl       pgtype.Text        `json:"file_url"`
	CreatedAt     time.Time          `json:"created_at"`
}

type User struct {
	ID            uuid.UUID `json:"id"`
	Email         string    `json:"email"`
	PasswordHash  string    `json:"password_hash"`
	EmailVerified bool      `json:"email_verified"`
	Status        string    `json:"status"`
	CreatedAt     time.Time `json:"created_at"`
	UpdatedAt     time.Time `json:"updated_at"`
}

type UserRole struct {
	UserID    uuid.UUID `json:"user_id"`
	RoleID    uuid.UUID `json:"role_id"`
	SectionID uuid.UUID `json:"section_id"`
}
