// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: news.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createNews = `-- name: CreateNews :exec
INSERT INTO news (title_ru, body_ru, title_en, body_en, pinned)
VALUES ($1,$2,$3,$4,$5)
`

type CreateNewsParams struct {
	TitleRu string `json:"title_ru"`
	BodyRu  string `json:"body_ru"`
	TitleEn string `json:"title_en"`
	BodyEn  string `json:"body_en"`
	Pinned  bool   `json:"pinned"`
}

func (q *Queries) CreateNews(ctx context.Context, arg CreateNewsParams) error {
	_, err := q.db.Exec(ctx, createNews,
		arg.TitleRu,
		arg.BodyRu,
		arg.TitleEn,
		arg.BodyEn,
		arg.Pinned,
	)
	return err
}

const getNews = `-- name: GetNews :one
SELECT id, title_ru, body_ru, title_en, body_en, pinned, published_at FROM news WHERE id = $1
`

func (q *Queries) GetNews(ctx context.Context, id uuid.UUID) (News, error) {
	row := q.db.QueryRow(ctx, getNews, id)
	var i News
	err := row.Scan(
		&i.ID,
		&i.TitleRu,
		&i.BodyRu,
		&i.TitleEn,
		&i.BodyEn,
		&i.Pinned,
		&i.PublishedAt,
	)
	return i, err
}

const listNews = `-- name: ListNews :many
SELECT id, title_ru, body_ru, title_en, body_en, pinned, published_at FROM news ORDER BY pinned DESC, published_at DESC
`

func (q *Queries) ListNews(ctx context.Context) ([]News, error) {
	rows, err := q.db.Query(ctx, listNews)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []News
	for rows.Next() {
		var i News
		if err := rows.Scan(
			&i.ID,
			&i.TitleRu,
			&i.BodyRu,
			&i.TitleEn,
			&i.BodyEn,
			&i.Pinned,
			&i.PublishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
