// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: profiles.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getProfile = `-- name: GetProfile :one
SELECT user_id, surname, name, patronymic, birth_date, city, academic_degree, affiliation, position, phone, postal_address, consent_data_processing, consent_data_transfer, updated_at FROM profiles WHERE user_id = $1
`

func (q *Queries) GetProfile(ctx context.Context, userID uuid.UUID) (Profile, error) {
	row := q.db.QueryRow(ctx, getProfile, userID)
	var i Profile
	err := row.Scan(
		&i.UserID,
		&i.Surname,
		&i.Name,
		&i.Patronymic,
		&i.BirthDate,
		&i.City,
		&i.AcademicDegree,
		&i.Affiliation,
		&i.Position,
		&i.Phone,
		&i.PostalAddress,
		&i.ConsentDataProcessing,
		&i.ConsentDataTransfer,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertProfile = `-- name: UpsertProfile :exec
INSERT INTO profiles (
  user_id, surname, name, patronymic, birth_date, city,
  academic_degree, affiliation, position, phone,
  postal_address, consent_data_processing, consent_data_transfer
) VALUES (
  $1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13
)
ON CONFLICT (user_id) DO UPDATE SET
  surname = EXCLUDED.surname,
  name = EXCLUDED.name,
  patronymic = EXCLUDED.patronymic,
  birth_date = EXCLUDED.birth_date,
  city = EXCLUDED.city,
  academic_degree = EXCLUDED.academic_degree,
  affiliation = EXCLUDED.affiliation,
  position = EXCLUDED.position,
  phone = EXCLUDED.phone,
  postal_address = EXCLUDED.postal_address,
  consent_data_processing = EXCLUDED.consent_data_processing,
  consent_data_transfer = EXCLUDED.consent_data_transfer,  updated_at = now()
`

type UpsertProfileParams struct {
	UserID                uuid.UUID   `json:"user_id"`
	Surname               string      `json:"surname"`
	Name                  string      `json:"name"`
	Patronymic            string      `json:"patronymic"`
	BirthDate             time.Time   `json:"birth_date"`
	City                  string      `json:"city"`
	AcademicDegree        pgtype.Text `json:"academic_degree"`
	Affiliation           string      `json:"affiliation"`
	Position              string      `json:"position"`
	Phone                 string      `json:"phone"`
	PostalAddress         string      `json:"postal_address"`
	ConsentDataProcessing bool        `json:"consent_data_processing"`
	ConsentDataTransfer   bool        `json:"consent_data_transfer"`
}

func (q *Queries) UpsertProfile(ctx context.Context, arg UpsertProfileParams) error {
	_, err := q.db.Exec(ctx, upsertProfile,
		arg.UserID,
		arg.Surname,
		arg.Name,
		arg.Patronymic,
		arg.BirthDate,
		arg.City,
		arg.AcademicDegree,
		arg.Affiliation,
		arg.Position,
		arg.Phone,
		arg.PostalAddress,
		arg.ConsentDataProcessing,
		arg.ConsentDataTransfer,
	)
	return err
}
