// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sections.sql

package sqlc

import (
	"context"
)

const createSection = `-- name: CreateSection :exec
INSERT INTO sections (title_ru, title_en, sort_order)
VALUES ($1, $2, $3)
`

type CreateSectionParams struct {
	TitleRu   string `json:"title_ru"`
	TitleEn   string `json:"title_en"`
	SortOrder int32  `json:"sort_order"`
}

func (q *Queries) CreateSection(ctx context.Context, arg CreateSectionParams) error {
	_, err := q.db.Exec(ctx, createSection, arg.TitleRu, arg.TitleEn, arg.SortOrder)
	return err
}

const listSections = `-- name: ListSections :many
SELECT id, title_ru, title_en, sort_order FROM sections ORDER BY sort_order
`

func (q *Queries) ListSections(ctx context.Context) ([]Section, error) {
	rows, err := q.db.Query(ctx, listSections)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Section
	for rows.Next() {
		var i Section
		if err := rows.Scan(
			&i.ID,
			&i.TitleRu,
			&i.TitleEn,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
