// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sessions.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createSession = `-- name: CreateSession :exec
INSERT INTO refresh_sessions (user_id, token_hash, expires_at)
VALUES ($1, $2, $3)
`

type CreateSessionParams struct {
	UserID    uuid.UUID `json:"user_id"`
	TokenHash string    `json:"token_hash"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.Exec(ctx, createSession, arg.UserID, arg.TokenHash, arg.ExpiresAt)
	return err
}

const getSessionByToken = `-- name: GetSessionByToken :one
SELECT id, user_id, token_hash, revoked_at, expires_at, created_at FROM refresh_sessions WHERE token_hash = $1
`

func (q *Queries) GetSessionByToken(ctx context.Context, tokenHash string) (RefreshSession, error) {
	row := q.db.QueryRow(ctx, getSessionByToken, tokenHash)
	var i RefreshSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.RevokedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const revokeSession = `-- name: RevokeSession :exec
UPDATE refresh_sessions SET revoked_at = now() WHERE id = $1
`

func (q *Queries) RevokeSession(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeSession, id)
	return err
}
